enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [Music]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "6.51.53"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.225.0-dev.21"
integrations-version = "v0.152.0-dev.12"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.16.39"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.225.0-dev.21"
integrations-version = "v0.152.0-dev.12"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Hide videos based on duration ' 'Force disable Shorts dim' 'Force snackbar theme' 'Custom branding name YouTube' 'Add splash animation' ' Insert position'"
arch = "arm64-v8a"



[twitter-non-monet]
build-mode = "apk"
version = "10.42.0-release.0"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
patches-version = "v1.30.0"
integrations-version = "v1.19.0"
rv-brand = "Piko Patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Debug Menu' 'Customize Inline action Bar items' 'Hide hidden replies' 'Hide Buy Premium Banner' 'Round off numbers' 'Hide hidden replies' 'Hide Banner' 'Hide Live Threads' 'Disable auto timeline scroll on launch' 'Add ability to copy media link' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Show poll results' 'Open links with app chooser' 'Hide promote button' 'Force enable translate' 'Profile tabs customisation'"
excluded-patches = "'Dynamic color'"
arch = "arm64-v8a"

[Reddit]
app-name = "Reddit"
version = "2024.17.0"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.225.0-dev.21"
integrations-version = "v0.152.0-dev.12"
rv-brand = "RVX"
arch = "arm64-v8a"

