enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [Music]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.223.0-dev.20"
integrations-version = "v0.150.0-dev.4"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.11.38"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.223.0-dev.20"
integrations-version = "v0.150.0-dev.4"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
arch = "arm64-v8a"



[twitter-non-monet]
build-mode = "apk"
version = "10.34.0-release.0"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko Patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons'"
excluded-patches = "'Dynamic color'"
arch = "arm64-v8a"
