enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

[Music-ReX]
app-name = "Music"
build-mode = "module"
version = "6.36.54"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "Bitrate default value"
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "module"
version = "19.09.38"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
