enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [Music]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "7.08.53"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.22"
integrations-version = "v0.154.0-dev.7"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.25.39"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.22"
integrations-version = "v0.154.0-dev.7"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
arch = "arm64-v8a"
