enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config


[Music-ReX]
app-name = "Music"
build-mode = "both"
version = "6.41.59"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"

[YouTube-ReX]
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
version = "19.11.36"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
